const FLAGS: Record<string, string> = {
  'MEXICO': '🇲🇽', 'MÉXICO': '🇲🇽',
  'SUDAFRICA': '🇿🇦', 'SUDÁFRICA': '🇿🇦',
  'COREA': '🇰🇷', 'REP. CHECA': '🇨🇿',
  'CANADA': '🇨🇦', 'CANADÁ': '🇨🇦',
  'BOSNIA': '🇧🇦', 'USA': '🇺🇸', 'ESTADOS UNIDOS': '🇺🇸',
  'PARAGUAY': '🇵🇾', 'QATAR': '🇶🇦',
  'SUIZA': '🇨🇭', 'BRASIL': '🇧🇷',
  'MARRUECOS': '🇲🇦', 'HAITI': '🇭🇹', 'HAITÍ': '🇭🇹',
  'ESCOCIA': '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'AUSTRALIA': '🇦🇺',
  'TURQUÍA': '🇹🇷', 'TURQUIA': '🇹🇷',
  'ALEMANIA': '🇩🇪', 'CURAZAO': '🇨🇼',
  'PAISES B.': '🇳🇱', 'PAÍSES B.': '🇳🇱', 'PAISES BAJOS': '🇳🇱',
  'JAPÓN': '🇯🇵', 'JAPON': '🇯🇵',
  'COSTA DE M.': '🇨🇮', 'ECUADOR': '🇪🇨',
  'SUECIA': '🇸🇪', 'TUNEZ': '🇹🇳', 'TÚNEZ': '🇹🇳',
  'EPAÑA': '🇪🇸', 'ESPAÑA': '🇪🇸', 'ESPANA': '🇪🇸',
  'CABO VERDE': '🇨🇻', 'BELGICA': '🇧🇪', 'BÉLGICA': '🇧🇪',
  'EGIPTO': '🇪🇬', 'ARABIA S.': '🇸🇦', 'ARABIA SAUDITA': '🇸🇦',
  'URUGUAY': '🇺🇾', 'IRAN': '🇮🇷', 'IRÁN': '🇮🇷',
  'NUEVA ZELAN': '🇳🇿', 'NUEVA ZELANDA': '🇳🇿',
  'FRANCIA': '🇫🇷', 'SENEGAL': '🇸🇳',
  'IRAK': '🇮🇶', 'NORUEGA': '🇳🇴',
  'ARGENTINA': '🇦🇷', 'ARGELIA': '🇩🇿',
  'AUSTRIA': '🇦🇹', 'JORDANIA': '🇯🇴',
  'PORTUGAL': '🇵🇹', 'RIO CONGO': '🇨🇩', 'RIOCONGO': '🇨🇩',
  'INGLATERRA': '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'ENGLAND': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'CROACIA': '🇭🇷', 'GHANA': '🇬🇭',
  'PANAMA': '🇵🇦', 'PANAMÁ': '🇵🇦',
  'UZBEKISTAN': '🇺🇿', 'UZBEKISTÁN': '🇺🇿',
  'COLOMBIA': '🇨🇴', 'NIGERIA': '🇳🇬',
  'CAMERUN': '🇨🇲', 'CAMERÚN': '🇨🇲',
  'PERU': '🇵🇪', 'PERÚ': '🇵🇪',
  'CHILE': '🇨🇱', 'VENEZUELA': '🇻🇪',
  'COSTA RICA': '🇨🇷', 'HONDURAS': '🇭🇳',
  'JAMAICA': '🇯🇲', 'ISRAEL': '🇮🇱',
  'SERBIA': '🇷🇸', 'DINAMARCA': '🇩🇰',
  'POLONIA': '🇵🇱', 'UCRANIA': '🇺🇦',
  'GEORGIA': '🇬🇪', 'ALBANIA': '🇦🇱',
}

export function getFlag(teamName: string): string {
  const key = teamName.trim().toUpperCase()
  return FLAGS[key] ?? '🏳️'
}
