// ISO 3166-1 alpha-2 codes for flagcdn.com
// Usage: https://flagcdn.com/w40/{code}.png
const CODES: Record<string, string> = {
  'MEXICO': 'mx', 'MÉXICO': 'mx',
  'SUDAFRICA': 'za', 'SUDÁFRICA': 'za',
  'COREA': 'kr',
  'CANADA': 'ca', 'CANADÁ': 'ca',
  'BOSNIA': 'ba',
  'USA': 'us', 'ESTADOS UNIDOS': 'us',
  'PARAGUAY': 'py',
  'QATAR': 'qa',
  'SUIZA': 'ch',
  'BRASIL': 'br',
  'MARRUECOS': 'ma',
  'HAITI': 'ht', 'HAITÍ': 'ht',
  'ESCOCIA': 'gb-sct',
  'AUSTRALIA': 'au',
  'TURQUIA': 'tr', 'TURQUÍA': 'tr',
  'ALEMANIA': 'de',
  'CURAZAO': 'cw',
  'PAISES B.': 'nl', 'PAÍSES B.': 'nl', 'PAISES BAJOS': 'nl', 'PAÍSES BAJOS': 'nl', 'HOLANDA': 'nl',
  'JAPON': 'jp', 'JAPÓN': 'jp',
  'COSTA DE M.': 'ci', 'COSTA DE MARFIL': 'ci',
  'ECUADOR': 'ec',
  'SUECIA': 'se',
  'TUNEZ': 'tn', 'TÚNEZ': 'tn',
  'EPAÑA': 'es', 'ESPAÑA': 'es', 'ESPANA': 'es',
  'CABO VERDE': 'cv',
  'BELGICA': 'be', 'BÉLGICA': 'be',
  'EGIPTO': 'eg',
  'ARABIA S.': 'sa', 'ARABIA SAUDITA': 'sa', 'ARABIA SAUDI': 'sa',
  'URUGUAY': 'uy',
  'IRAN': 'ir', 'IRÁN': 'ir',
  'NUEVA ZELAN': 'nz', 'NUEVA ZELANDA': 'nz', 'NUEVA ZELAN.': 'nz',
  'FRANCIA': 'fr',
  'SENEGAL': 'sn',
  'IRAK': 'iq',
  'NORUEGA': 'no',
  'ARGENTINA': 'ar',
  'ARGELIA': 'dz',
  'AUSTRIA': 'at',
  'JORDANIA': 'jo',
  'PORTUGAL': 'pt',
  'RIO CONGO': 'cd', 'RIOCONGO': 'cd', 'CONGO': 'cd', 'DR CONGO': 'cd',
  'INGLATERRA': 'gb-eng', 'ENGLAND': 'gb-eng',
  'CROACIA': 'hr',
  'GHANA': 'gh',
  'PANAMA': 'pa', 'PANAMÁ': 'pa',
  'UZBEKISTAN': 'uz', 'UZBEKISTÁN': 'uz',
  'COLOMBIA': 'co',
  'NIGERIA': 'ng',
  'KENYA': 'ke',
  'CAMERUN': 'cm', 'CAMERÚN': 'cm',
  'PERU': 'pe', 'PERÚ': 'pe',
  'CHILE': 'cl',
  'VENEZUELA': 've',
  'COSTA RICA': 'cr',
  'HONDURAS': 'hn',
  'JAMAICA': 'jm',
  'ISRAEL': 'il',
  'SERBIA': 'rs',
  'DINAMARCA': 'dk',
  'FINLANDIA': 'fi',
  'ESLOVENIA': 'si',
  'HUNGRIA': 'hu', 'HUNGRÍA': 'hu',
  'ESLOVAQUIA': 'sk',
  'RUMANIA': 'ro', 'RUMANÍA': 'ro',
  'GRECIA': 'gr',
  'POLONIA': 'pl',
  'UCRANIA': 'ua',
  'GEORGIA': 'ge',
  'ALBANIA': 'al',
  'KAZAJISTAN': 'kz',
  'TAILANDIA': 'th',
  'VIETNAM': 'vn',
  'INDONESIA': 'id',
}

export function getFlagUrl(teamName: string): string | null {
  const code = CODES[teamName.trim().toUpperCase()]
  return code ? `https://flagcdn.com/w40/${code}.png` : null
}

// Kept for backwards compat — returns empty string instead of emoji on no match
export function getFlag(teamName: string): string {
  return ''
}
