// ISO 3166-1 alpha-2 codes for flagcdn.com
// Usage: https://flagcdn.com/w40/{code}.png
const CODES: Record<string, string> = {
  'MEXICO': 'mx', 'MÉXICO': 'mx',
  'SUDAFRICA': 'za', 'SUDÁFRICA': 'za',
  'COREA': 'kr',
  'CANADA': 'ca', 'CANADÁ': 'ca', 'CÁNADA': 'ca',
  'REP. CHECA': 'cz', 'REPUBLICA CHECA': 'cz', 'REPÚBLICA CHECA': 'cz',
  'BOSNIA AND HERZEGOVINA': 'ba', 'BOSNIA & HERZEGOVINA': 'ba',
  'BOSNIA': 'ba',
  'USA': 'us', 'ESTADOS UNIDOS': 'us',
  'PARAGUAY': 'py',
  'QATAR': 'qa',
  'SUIZA': 'ch',
  'BRASIL': 'br',
  'MARRUECOS': 'ma',
  'HAITI': 'ht', 'HAITÍ': 'ht',
  'ESCOCIA': 'gb-sct',
  'AUSTRALIA': 'au',
  'TURQUIA': 'tr', 'TURQUÍA': 'tr',
  'ALEMANIA': 'de',
  'CURAZAO': 'cw',
  'PAISES B.': 'nl', 'PAÍSES B.': 'nl', 'PAISES BAJOS': 'nl', 'PAÍSES BAJOS': 'nl', 'HOLANDA': 'nl',
  'JAPON': 'jp', 'JAPÓN': 'jp',
  'COSTA DE M.': 'ci', 'COSTA DE MARFIL': 'ci',
  'ECUADOR': 'ec',
  'SUECIA': 'se',
  'TUNEZ': 'tn', 'TÚNEZ': 'tn',
  'EPAÑA': 'es', 'ESPAÑA': 'es', 'ESPANA': 'es',
  'CABO VERDE': 'cv',
  'BELGICA': 'be', 'BÉLGICA': 'be',
  'EGIPTO': 'eg',
  'ARABIA S.': 'sa', 'ARABIA SAUDITA': 'sa', 'ARABIA SAUDI': 'sa',
  'URUGUAY': 'uy',
  'IRAN': 'ir', 'IRÁN': 'ir',
  'NUEVA ZELAN': 'nz', 'NUEVA ZELANDA': 'nz', 'NUEVA ZELAN.': 'nz',
  'FRANCIA': 'fr',
  'SENEGAL': 'sn',
  'IRAK': 'iq',
  'NORUEGA': 'no',
  'ARGENTINA': 'ar',
  'ARGELIA': 'dz',
  'AUSTRIA': 'at',
  'JORDANIA': 'jo',
  'PORTUGAL': 'pt',
  'RIO CONGO': 'cd', 'RIOCONGO': 'cd', 'CONGO': 'cd', 'DR CONGO': 'cd',
  'INGLATERRA': 'gb-eng', 'ENGLAND': 'gb-eng',
  'CROACIA': 'hr',
  'GHANA': 'gh',
  'PANAMA': 'pa', 'PANAMÁ': 'pa',
  'UZBEKISTAN': 'uz', 'UZBEKISTÁN': 'uz',
  'COLOMBIA': 'co',
  'NIGERIA': 'ng',
  'KENYA': 'ke',
  'CAMERUN': 'cm', 'CAMERÚN': 'cm',
  'PERU': 'pe', 'PERÚ': 'pe',
  'CHILE': 'cl',
  'VENEZUELA': 've',
  'COSTA RICA': 'cr',
  'HONDURAS': 'hn',
  'JAMAICA': 'jm',
  'ISRAEL': 'il',
  'SERBIA': 'rs',
  'DINAMARCA': 'dk',
  'FINLANDIA': 'fi',
  'ESLOVENIA': 'si',
  'HUNGRIA': 'hu', 'HUNGRÍA': 'hu',
  'ESLOVAQUIA': 'sk',
  'RUMANIA': 'ro', 'RUMANÍA': 'ro',
  'GRECIA': 'gr',
  'POLONIA': 'pl',
  'UCRANIA': 'ua',
  'GEORGIA': 'ge',
  'ALBANIA': 'al',
  'KAZAJISTAN': 'kz',
  'TAILANDIA': 'th',
  'VIETNAM': 'vn',
  'INDONESIA': 'id',
}

// English names as returned by the API (home_team_name_en)
const CODES_EN: Record<string, string> = {
  'MEXICO': 'mx', 'ECUADOR': 'ec', 'JAMAICA': 'jm', 'VENEZUELA': 've',
  'UNITED STATES': 'us', 'PANAMA': 'pa', 'URUGUAY': 'uy', 'UZBEKISTAN': 'uz',
  'CANADA': 'ca', 'HONDURAS': 'hn', 'PARAGUAY': 'py', 'NEW ZEALAND': 'nz',
  'MOROCCO': 'ma', 'PORTUGAL': 'pt', 'ARGENTINA': 'ar', 'HAITI': 'ht',
  'SPAIN': 'es', 'COLOMBIA': 'co', 'BRAZIL': 'br', 'SAUDI ARABIA': 'sa',
  'FRANCE': 'fr', 'UKRAINE': 'ua', 'EGYPT': 'eg',
  'DEMOCRATIC REPUBLIC OF THE CONGO': 'cd',
  'GERMANY': 'de', 'JAPAN': 'jp', 'CHILE': 'cl', 'BELGIUM': 'be',
  'ENGLAND': 'gb-eng', 'SENEGAL': 'sn', 'BOSNIA AND HERZEGOVINA': 'ba', 'ALGERIA': 'dz',
  'NETHERLANDS': 'nl', 'TURKEY': 'tr', 'GEORGIA': 'ge', 'THAILAND': 'th',
  'AUSTRALIA': 'au', 'NIGERIA': 'ng', 'ROMANIA': 'ro', 'SOUTH KOREA': 'kr',
  'CROATIA': 'hr', 'SLOVAKIA': 'sk', 'IRAN': 'ir', 'PERU': 'pe',
  'SWITZERLAND': 'ch', 'NORWAY': 'no', 'COSTA RICA': 'cr', 'ISRAEL': 'il',
  'SERBIA': 'rs', 'DENMARK': 'dk', 'FINLAND': 'fi', 'SLOVENIA': 'si',
  'HUNGARY': 'hu', 'GREECE': 'gr', 'POLAND': 'pl', 'ALBANIA': 'al',
  'KAZAKHSTAN': 'kz', 'VIETNAM': 'vn', 'INDONESIA': 'id', 'CAPE VERDE': 'cv',
  'SCOTLAND': 'gb-sct', 'CZECH REPUBLIC': 'cz', 'SWEDEN': 'se', 'IRAQ': 'iq',
  'IVORY COAST': 'ci', 'TUNISIA': 'tn', 'JORDAN': 'jo', 'CURAÇAO': 'cw',
  'SOUTH AFRICA': 'za',
}

export function getFlagUrl(teamName: string): string | null {
  const key = teamName.trim().toUpperCase()
  const code = CODES[key] ?? CODES_EN[key]
  return code ? `https://flagcdn.com/w40/${code}.png` : null
}
