// Maps Excel team names (Spanish/abbreviated) → API canonical names
export const TEAM_MAPPING: Record<string, string> = {
  // Direct matches
  'MEXICO': 'Mexico',
  'MÉXICO': 'Mexico',
  'SUDAFRICA': 'South Africa',
  'SUDÁFRICA': 'South Africa',
  'COREA': 'South Korea',
  'REP. CHECA': 'Czech Republic',
  'REPUBLICA CHECA': 'Czech Republic',
  'CANADA': 'Canada',
  'CANADÁ': 'Canada',
  'CÁNADA': 'Canada',
  'BOSNIA': 'Bosnia and Herzegovina',
  'BOSNIA & HERZEGOVINA': 'Bosnia and Herzegovina',
  'BOSNIA-HERZEGOVINA': 'Bosnia and Herzegovina',
  'CZECHIA': 'Czech Republic',
  'DR CONGO': 'Democratic Republic of the Congo',
  'USA': 'United States',
  'ESTADOS UNIDOS': 'United States',
  'PARAGUAY': 'Paraguay',
  'QATAR': 'Qatar',
  'SUIZA': 'Switzerland',
  'BRASIL': 'Brazil',
  'MARRUECOS': 'Morocco',
  'HAITI': 'Haiti',
  'HAITÍ': 'Haiti',
  'ESCOCIA': 'Scotland',
  'AUSTRALIA': 'Australia',
  'TURQUIA': 'Turkey',
  'TURQUÍA': 'Turkey',
  'ALEMANIA': 'Germany',
  'CURAZAO': 'Curaçao',
  'PAISES B.': 'Netherlands',
  'PAÍSES B.': 'Netherlands',
  'PAISES BAJOS': 'Netherlands',
  'PAÍSES BAJOS': 'Netherlands',
  'HOLANDA': 'Netherlands',
  'JAPON': 'Japan',
  'JAPÓN': 'Japan',
  'COSTA DE M.': 'Ivory Coast',
  'COSTA DE MARFIL': 'Ivory Coast',
  'ECUADOR': 'Ecuador',
  'SUECIA': 'Sweden',
  'TUNEZ': 'Tunisia',
  'TÚNEZ': 'Tunisia',
  'EPAÑA': 'Spain',
  'ESPAÑA': 'Spain',
  'ESPANA': 'Spain',
  'CABO VERDE': 'Cape Verde',
  'BELGICA': 'Belgium',
  'BÉLGICA': 'Belgium',
  'EGIPTO': 'Egypt',
  'ARABIA S.': 'Saudi Arabia',
  'ARABIA SAUDITA': 'Saudi Arabia',
  'ARABIA SAUDI': 'Saudi Arabia',
  'URUGUAY': 'Uruguay',
  'IRAN': 'Iran',
  'IRÁN': 'Iran',
  'NUEVA ZELAN': 'New Zealand',
  'NUEVA ZELANDA': 'New Zealand',
  'NUEVA ZELAN.': 'New Zealand',
  'FRANCIA': 'France',
  'SENEGAL': 'Senegal',
  'IRAK': 'Iraq',
  'NORUEGA': 'Norway',
  'ARGENTINA': 'Argentina',
  'ARGELIA': 'Algeria',
  'AUSTRIA': 'Austria',
  'JORDANIA': 'Jordan',
  'PORTUGAL': 'Portugal',
  'RIO CONGO': 'Democratic Republic of the Congo',
  'CONGO': 'Democratic Republic of the Congo',
  'ENGLAND': 'England',
  'INGLATERRA': 'England',
  'CROACIA': 'Croatia',
  'GHANA': 'Ghana',
  'PANAMA': 'Panama',
  'PANAMÁ': 'Panama',
  'UZBEKISTAN': 'Uzbekistan',
  'UZBEKISTÁN': 'Uzbekistan',
  'COLOMBIA': 'Colombia',
  'NIGERIA': 'Nigeria',
  'KENYA': 'Kenya',
  'CAMERUN': 'Cameroon',
  'CAMERÚN': 'Cameroon',
  'PERU': 'Peru',
  'PERÚ': 'Peru',
  'CHILE': 'Chile',
  'VENEZUELA': 'Venezuela',
  'COSTA RICA': 'Costa Rica',
  'HONDURAS': 'Honduras',
  'JAMAICA': 'Jamaica',
  'ISRAEL': 'Israel',
  'SERBIA': 'Serbia',
  'DINAMARCA': 'Denmark',
  'FINLANDIA': 'Finland',
  'ESLOVENIA': 'Slovenia',
  'HUNGRIA': 'Hungary',
  'HUNGRÍA': 'Hungary',
  'ESLOVAQUIA': 'Slovakia',
  'RUMANIA': 'Romania',
  'RUMANÍA': 'Romania',
  'GRECIA': 'Greece',
  'POLONIA': 'Poland',
  'UCRANIA': 'Ukraine',
  'GEORGIA': 'Georgia',
  'ALBANIA': 'Albania',
  'KAZAJISTAN': 'Kazakhstan',
  'TAILANDIA': 'Thailand',
  'VIETNAM': 'Vietnam',
  'INDONESIA': 'Indonesia',
}

export function normalizeTeamName(excelName: string): string {
  const upper = excelName.trim().toUpperCase()
  return TEAM_MAPPING[upper] ?? excelName.trim()
}

// Phase name normalization
export const PHASE_MAPPING: Record<string, string> = {
  'PRIMERA FECHA': 'PRIMERA_FECHA',
  'SEGUNDA FECHA': 'SEGUNDA_FECHA',
  'TERCERA FECHA': 'TERCERA_FECHA',
  'DIECISESAVOS': 'DIECISEISAVOS',
  'DIECISEISAVOS': 'DIECISEISAVOS',
  'OCTAVOS': 'OCTAVOS',
  'CUARTOS': 'CUARTOS',
  'SEMIFINALES': 'SEMIFINALES',
  'FINAL': 'FINAL',
}

export function normalizePhase(raw: string): string {
  const upper = raw.trim().toUpperCase()
  return PHASE_MAPPING[upper] ?? upper.replace(/\s+/g, '_')
}
